[package]
name = "rust_csv_to_json"
version = "0.1.0"
authors = ["StephaneC <Stephane.castrec@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.26.0"
